server:
   port: 8081
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  resources:
    static-locations:
    #- file:D:/gsv/WMSLayer_image
  datasource:
    #url: jdbc:mysql://127.0.0.1:3306/wmsall_0705?serverTimezone=GMT%2B8&useSSL=false
    url: jdbc:mysql://127.0.0.1:3306/test_wms?serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

#logging:
#  file: E:\OGC Portal系统开发\temp
#  level:
#    com.gsv.querywmslist.querywmslist.service.LayerQueryService: debug